// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import ActivityGraphController from "./activity_graph_controller"
import DropdownController from "./dropdown_controller"
import FlashController from "./flash_controller"
import ConnectionFormController from "./connection_form_controller"
import MobileMenuController from "./mobile_menu_controller"

application.register("hello", HelloController)
application.register("activity-graph", ActivityGraphController)
application.register("dropdown", DropdownController)
application.register("flash", FlashController)
application.register("connection-form", ConnectionFormController)
application.register("mobile-menu", MobileMenuController)
